/*
 * Copyright 2026 AceMQ.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.acemq.amqp.codec.protobuf;

import java.util.Locale;
import java.util.Objects;

import org.acemq.amqp.api.AceMqException;
import org.acemq.amqp.api.Codec;
import org.jspecify.annotations.Nullable;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.Message;
import com.google.protobuf.MessageLite;
import com.google.protobuf.Parser;

/**
 * Reads and writes Protocol Buffers.
 *
 * <p>Like Avro, and for the same reason, there is no {@code asProtobuf()}. Protobuf bytes say
 * nothing about which message they are: field numbers and wire types, and no names or type. A
 * reader must be told what to parse them as, so this is reached through
 * {@code publisher.as(ProtobufCodec.of(OrderPlaced.parser()))}.
 *
 * <p>One codec per message type, which is not a limitation so much as a description of how
 * protobuf is used: a destination carries one kind of message, and that is what makes the bytes
 * interpretable at all. A destination that needs to carry several has to say which is which, and
 * the protobuf answer to that is a wrapper message with a {@code oneof} — a decision about the
 * schema rather than about the transport, so it belongs in the {@code .proto} file.
 *
 * <p>Evolution is the format's own affair and works without anything here: readers ignore fields
 * they do not know and use defaults for fields that are absent, provided nobody reuses a field
 * number. Nothing in this codec can protect against a reused number, and nothing can detect it
 * either — the bytes are valid and mean something else. Reserve retired numbers in the schema.
 */
public final class ProtobufCodec implements Codec {

    private static final String CONTENT_TYPE = "application/x-protobuf";

    private final Parser<? extends Message> parser;
    private final String typeName;

    private ProtobufCodec(Parser<? extends Message> parser, String typeName) {
        this.parser = parser;
        this.typeName = typeName;
    }

    /**
     * @param parser the generated type's parser, as in {@code OrderPlaced.parser()}
     * @param <T> message type
     * @return a codec for that one message type
     */
    public static <T extends Message> ProtobufCodec of(Parser<T> parser) {
        return new ProtobufCodec(Objects.requireNonNull(parser, "parser"), "a protobuf message");
    }

    /**
     * The same thing, given the class instead of its parser.
     *
     * @param type a class generated by protoc
     * @param <T> message type
     * @return a codec for that one message type
     */
    @SuppressWarnings("unchecked")
    public static <T extends Message> ProtobufCodec of(Class<T> type) {
        Objects.requireNonNull(type, "type");
        try {
            // Every generated message has a static parser(). Reflection is used only here, once,
            // when the codec is built, and never on the path a message travels.
            Parser<T> parser = (Parser<T>) type.getMethod("parser").invoke(null);
            return new ProtobufCodec(parser, type.getName());
        } catch (ReflectiveOperationException | ClassCastException e) {
            throw new AceMqException(type.getName() + " does not look like a class protoc generated: it needs a"
                    + " static parser() method", e);
        }
    }

    @Override
    public String contentType() {
        return CONTENT_TYPE;
    }

    @Override
    public byte[] encode(Object payload) {
        if (payload instanceof MessageLite) {
            return ((MessageLite) payload).toByteArray();
        }
        throw new AceMqException("the protobuf codec publishes generated messages and was given a "
                + payload.getClass().getName() + ". Publish with asJson() to have an ordinary object encoded,"
                + " or generate the message type from a .proto file.");
    }

    @Override
    public <T> T decode(byte[] body, Class<T> target) {
        Message parsed;
        try {
            parsed = parser.parseFrom(body);
        } catch (InvalidProtocolBufferException e) {
            throw new AceMqException("could not decode a message as " + typeName + ": " + e.getMessage(), e);
        }
        if (!target.isInstance(parsed)) {
            // Worth its own message. Protobuf will happily parse bytes meant for one message as
            // another when the field numbers overlap, so this mismatch is the difference between
            // a wrong answer and an error.
            throw new AceMqException("this codec parses " + parsed.getClass().getName() + " and " + target.getName()
                    + " was asked for. A codec is built for one message type; use a separate consumer, or a"
                    + " wrapper message with a oneof.");
        }
        return target.cast(parsed);
    }

    @Override
    public boolean canDecode(@Nullable String contentType) {
        if (contentType == null) {
            // Protobuf bytes are not recognisable and parse quietly into nonsense more often
            // than they fail, so this never volunteers.
            return false;
        }
        String type = contentType.toLowerCase(Locale.ROOT);
        return type.startsWith(CONTENT_TYPE) || type.startsWith("application/protobuf") || type.contains("+protobuf");
    }

    @Override
    public String toString() {
        return "ProtobufCodec{" + typeName + "}";
    }
}
